version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./Dockerfile/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
      - ./Config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
#       - "443:443"
    volumes:
      - ./laravel:/var/www
      - ./Config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  database:
    image: mariadb:latest
    container_name: database
    environment:
        - "MYSQL_USERNAME=root"
        - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
    networks:
      - app-network


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
          - "MYSQL_USERNAME=root"
          - "MYSQL_ROOT_PASSWORD=secret"
          - "PMA_HOST=database"
      links:
          - database
      ports:
          - "8080:80"
      networks:
      - app-network
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: hostname
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "443:443"
      - "8880:80"
      - "8822:22"
# The logs directory can be mapped to the logs directory in the same director
# as the docker-compose file using the following entry under volumes:
# - ./logs:/var/log/gitlab
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
    restart: always
 

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local